# Generated by Django 5.1.6 on 2025-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_datamodel_delete_vehicleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
