# Generated by Django 5.1.6 on 2025-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_datamodel_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('camera1_image', models.TextField()),
                ('camera2_image', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
