# Generated by Django 5.1.6 on 2025-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicleevent_delete_datamodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicleevent',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='truck_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='event_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
