# Generated by Django 5.1.6 on 2025-02-28 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_vehicleevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleevent',
            name='event_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
