# Generated by Django 5.1.6 on 2025-03-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vehicleevent_trailer_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleevent',
            name='trailer_timestamp',
        ),
        migrations.RemoveField(
            model_name='vehicleevent',
            name='truck_timestamp',
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='truck_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
