# Generated by Django 5.1.6 on 2025-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_vehicleevent_trailer_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleevent',
            name='trailer_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleevent',
            name='truck_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='trailer_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleevent',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
